### ISSUE TITLE
Связи одного документа со всеми регистрами сведений.

### ISSUE THREAD

**Issue by Sbenik** [plastinin/diagramobject#5]
УТ 11.5 Открываю обработку в предприятии. Выбираю документ заказ клиента и все регистры сведений и получаю ошибку(с регистрами накоплений все работает нормально).
![Безымянный](https://user-images.githubusercontent.com/41571399/186620298-156e2aee-6f71-407e-a9d8-e5079606a322.png)

**Comment by Sbenik** [comment]
Сформированный текст диаграммы в файле
[Ошибка1.txt](https://github.com/plastinin/diagramobject/files/9423110/1.txt)

**Comment by malikov-pro** [comment]
Ломается на кавычках в
```
_РегистрСведений(ДатаЗагрузкиОтчетовКассЭвотор, "Дата загрузки отчетов "1С:Эвотор Офлайн"")
_РегистрСведений(СоответствиеНоменклатурыМобильногоПриложения1СЗаказы, "Соответствие номенклатуры мобильного приложения "1С: Заказы клиентов"")
_РегистрСведений(СоответствиеУсловийПродажМобильногоПриложения1СЗаказы, "Соответствие условий продаж мобильного приложения 1С: Заказы клиентов")
```

Уточнить в документации как экранировать, изменить алгоритм формирования комментария.

**Comment by malikov-pro** [comment]
Решается через экранирование символа
`_РегистрСведений(ДатаЗагрузкиОтчетовКассЭвотор, "Дата загрузки отчетов &#34;1С:Эвотор Офлайн <U+0022>")`

https://www.compart.com/en/unicode/U+0022

@plastinin какой формат выбираем?
