### ISSUE TITLE
При большом объеме данных картинка обрезается

### ISSUE THREAD

**Issue by Sbenik** [plastinin/diagramobject#6]
УТ 11.5. Открываю в предприятии обработку. Выбираю документ заказ клиента и все регистры накоплени. Картинка некорректно отображается (обрезается). Приходится копировать код, идти на сайт, там формировать картинку и в SVG она отображается корректно (сразу SVG в 1С отображать же можно)
![Безымянный1](https://user-images.githubusercontent.com/41571399/186621071-8228f726-0635-4e02-91e1-d769614cd754.png)
Код диаграммы в файле.
[Ошибка1.txt](https://github.com/plastinin/diagramobject/files/9423118/1.txt)

**Comment by malikov-pro** [comment]
Отображается как картинка, нужна обертка HTML c zoom через JS.
HTML c inline JS положить как текстовый макет.

**Comment by malikov-pro** [comment]
Картинка режется паблик сервисом. Вывод в HTML с масштабированием сделал из https://www.w3schools.com/howto/howto_js_image_zoom.asp

**Comment by plastinin** [comment]
![image](https://user-images.githubusercontent.com/11910528/188461615-c67b008e-0294-425c-97c6-e09583d98c72.png)

@Sbenik можно еще вот так попроьовать

**Comment by malikov-pro** [comment]
> @Sbenik можно еще вот так попроьовать

Пробовал, так же режет по горизонтали.

**Comment by yarsergo** [comment]
на тестовом примере [тест1.txt](https://github.com/user-attachments/files/17279333/1.txt)

/plantuml/**png**/ - режет картинку (только половина всего изображения)
![Картинка_тест1](https://github.com/user-attachments/assets/4509b8ad-620e-4629-9359-fbe97cb9b5c6)

помогает использование /plantuml/**svg/**
![Картинка_Test1](https://github.com/user-attachments/assets/a679ec1b-3121-4801-94a8-4e3b44a69eda)
