### ISSUE TITLE
Связи документа со всеми регистрами.

### ISSUE THREAD

**Issue by Sbenik** [plastinin/diagramobject#8]
УТ 11.5 Открываю в предприятии. Формирование по всем регистрам накоплений документа заказ клиента с реквизитами и связями не представляется возможным, сервер обработки изображений просто forbidden возвращает. Это в обработке.
![image](https://user-images.githubusercontent.com/41571399/186621411-0526a040-2102-4c81-9cc8-ea668c9d9727.png)
Если код диаграммы напрямую на сайт вставить то получим следующее.
[ОшибкаСайт.txt](https://github.com/plastinin/diagramobject/files/9423141/default.txt)
Код диаграммы.
[Ошибка1.txt](https://github.com/plastinin/diagramobject/files/9423143/1.txt)

**Comment by redokov** [comment]
Попробуйте вместо
!define v8_PUML https://raw.githubusercontent.com/plastinin/1ce-icons-for-plantuml/extended/dist/
написать:
!define v8_PUML https://raw.githubusercontent.com/plastinin/1ce-icons-for-plantuml/extended/dist

**Comment by malikov-pro** [comment]
Ограничение на размер файла при использовании паблик сервиса, разверните свой локальный например https://github.com/plantuml/plantuml-server
