### ISSUE TITLE
Табличные части не участвуют в отображении

### ISSUE THREAD

**Issue by Sbenik** [plastinin/diagramobject#9]
Справочник конфигурации и регистр сведений - добавлены мной, справочник Решения базы знаний - типовой. У справочника решения есть табличные части, в частности табличная часть Конфигурации, строки которой имеют ссылку на справочник Конфигурации. Соответственно табличные части не участвуют в отображении, что критично важно.
![image](https://user-images.githubusercontent.com/41571399/186645827-9fe03074-0821-41f6-8f8a-d30a0a7edc54.png)

**Comment by malikov-pro** [comment]
Прочитал пару раз, не понял как должно быть.

Нужны
* cf (блок с объектами из примера)
* код диаграммы "как должно быть"

**Comment by amidvn** [comment]
Имеется в виду, что, если ссылка на другой объект находится в табличной части (а не реквизитах шапки), то диаграмма не выстраивает связь

**Comment by Gisborn** [comment]
Табличные части и реквизиты ТЧ не попадают в генерацию кода схемы вообще.

Проблема была и 0.0.1, и в 0.0.3 она сохраняется.
Скачали 0.0.1 с Инфостарта, из гитхаба взял релиз 0.0.3.

Определение необходимости формирования ТЧЧ в 0.0.3 выглядит так:

```
&НаСервере
Функция ЭтоМетаданныеСТабличнойЧастью(СтрокаМетаданные)

	Возврат СтрНайти(СтрокаМетаданные, "Справочник.")
			ИЛИ СтрНайти(СтрокаМетаданные, "Документ.")
			ИЛИ СтрНайти(СтрокаМетаданные, "Обработка.") 
			ИЛИ СтрНайти(СтрокаМетаданные, "ПланВидовХарактеристик.")
			ИЛИ СтрНайти(СтрокаМетаданные, "Задача.") 
			ИЛИ СтрНайти(СтрокаМетаданные, "БизнесПроцесс.");
	
КонецФункции

```
При этом строка метаданных формируется из Команды, содержащей "_Справочник", Имени объекта МД (без типа) и синонима

```
&НаСервереБезКонтекста
Функция СформироватьСтрокуМетаданных(Команда, МетаданныеОбъекта)

	СинонимЭкранированный = ЭкранироватьСимволы(МетаданныеОбъекта.Синоним);

	Возврат СтрШаблон(
		"%1(%2, ""%3"")", 
		Команда, 
		МетаданныеОбъекта.Имя, 
		СинонимЭкранированный);

КонецФункции
```

Поэтому функция ЭтоМетаданныеСТабличнойЧастью() всегда возвращает Ложь.
Нужно либо менять параметры вызова, либо параметры поиска, либо в Команду после "_Справочник" добавить еще точку.

**Comment by yarsergo** [comment]
уже работают - при [v] формировании по реквизитам  отражаются через ---ИмяТЧ----
дополнительно для регистров - Измерения, Ресурсы и Реквизиты
![Пример2](https://github.com/user-attachments/assets/2d20581b-426c-4873-953c-cb218e27298f)

**Comment by malikov-pro** [comment]
@yarsergo прикрепляй issue к релизу и закрывай его.
